// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	model "policy-opa-pdp/pkg/model"

	mock "github.com/stretchr/testify/mock"
)

// PdpStatusSender is an autogenerated mock type for the PdpStatusSender type
type PdpStatusSender struct {
	mock.Mock
}

// SendPdpStatus provides a mock function with given fields: pdpStatus
func (_m *PdpStatusSender) SendPdpStatus(pdpStatus model.PdpStatus) error {
	ret := _m.Called(pdpStatus)

	if len(ret) == 0 {
		panic("no return value specified for SendPdpStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.PdpStatus) error); ok {
		r0 = rf(pdpStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPdpStatusSender creates a new instance of PdpStatusSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPdpStatusSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *PdpStatusSender {
	mock := &PdpStatusSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
